Add error handling
Seeing gitlab.com fetches fail with

   ssh_exchange_identification: read: Operation timed out
   fatal: Could not read from remote repository.

Added error diagnostics to show which repos are failing.

diff --git a/bin/update-repos b/bin/update-repos
--- a/bin/update-repos
+++ b/bin/update-repos
@@ -7,7 +7,7 @@ CUR_DIR=$(pwd);
 
 function fetch() {
    pushd "$(dirname "$CUR_DIR/$1")" > /dev/null || return
-   git fetch --prune
+   git fetch --prune || echo "Unable to fetch from $(git remote -v)"
    if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ] && [ "$(git remote | wc -l)" -ne 0 ] ; then
       git merge 1> /dev/null || echo "$1"
    fi
